//list
export const LIST_DOWNLOAD_START = "LIST_DOWNLOAD_START"
export const LIST_DOWNLOAD_OK = "LIST_DOWNLOAD_OK"
export const LIST_DOWNLOAD_FAIL = "LIST_DOWNLOAD_FAIL"

export const LIST_RESET = "LIST_RESET"

//show
export const ARTICLE_DOWNLOAD_START = "ARTICLE_DOWNLOAD_START"
export const ARTICLE_DOWNLOAD_OK = "ARTICLE_DOWNLOAD_OK"
export const ARTICLE_DOWNLOAD_FAIL = "ARTICLE_DOWNLOAD_FAIL"

export const ARTICLE_RESET = "ARTICLE_RESET"

//delete
export const ARTICLE_DELETE_START = "ARTICLE_DELETE_START"
export const ARTICLE_DELETE_OK = "ARTICLE_DELETE_OK"
export const ARTICLE_DELETE_FAIL = "ARTICLE_DELETE_FAIL"


export const ARTICLE_UPDATE_START = "ARTICLE_UPDATE_START"
export const ARTICLE_UPDATE_OK = "ARTICLE_UPDATE_OK"
export const ARTICLE_UPDATE_FAIL = "ARTICLE_UPDATE_FAIL"
export const ARTICLE_UPDATE_RESET = "ARTICLE_UPDATE_RESET"

export const ARTICLE_CREATE_START = "ARTICLE_CREATE_START"
export const ARTICLE_CREATE_OK = "ARTICLE_CREATE_OK"
export const ARTICLE_CREATE_FAIL = "ARTICLE_CREATE_FAIL"